active:
  communication:
    telegram:
      input: true
      output: true
      system_notifications: true
    gmail:
      input: false
      output: false
      system_notifications: false
    sms:
      input: false
      output: false
      system_notifications: false

plugins:
  telegram:
    token: "8570075240:AAHPpZL0AvvaKHZ2ydIf2xRAhnDiR73fbes"
    chat_id: "8658053670"

  gmail:
    email: "your-email@gmail.com"
    password: "your-email-password"
  
  sms:
    account_sid: "your-twilio-account-sid"
    auth_token: "your-twilio-auth-token"
    from_number: "+1234567890"
    to_number: "+0987654321"
